group=fun.bm.lophine
version=1.21.11-R0.1-SNAPSHOT
mcVersion=1.21.11
apiVersion=1.21.11
release=0
# 0 for skip release, 1 for pre-release, 2 for release

luminolRef=a20a54416546769b7a92027ef47a4b9315f5d6db

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
