group=fun.bm.lophine
version=1.21.11-R0.1-SNAPSHOT
mcVersion=1.21.11
apiVersion=1.21.11
release=0
# 0 for skip release, 1 for pre-release, 2 for release

luminolRef=bc9b3029bdf7434682b08c8a9c23eedb5e800e76

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
